CREATE TABLE `links` (
  `LINKID` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `LINKURL` text,
  `SOURCELINKID` int DEFAULT NULL,
  `SOURCEURL` text,
  `SOURCEORIGIN` enum('U','S') NOT NULL DEFAULT 'U',
  `ADDED` datetime NOT NULL,
  `SCANNED` enum('Y','N') NOT NULL DEFAULT 'N',
  `SUCCEEDED` enum('Y','N') DEFAULT NULL
) ENGINE=InnoDB;